"""add_description_to_tasks

Revision ID: 905c11c6a5e4
Revises: 24eb5ed526ac
Create Date: 2026-05-16 22:47:09.654057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '905c11c6a5e4'
down_revision: Union[str, Sequence[str], None] = '24eb5ed526ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('tasks', sa.Column('learning_objective', sa.Text(), nullable=True))
    op.add_column('tasks', sa.Column('connections', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'connections')
    op.drop_column('tasks', 'learning_objective')
    op.drop_column('tasks', 'description')
    # ### end Alembic commands ###
